# Generated by Django 5.2.14 on 2026-05-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_emergencycontact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
